### ISSUE TITLE
blog post on windpapi4j

### ISSUE THREAD

**Issue by fstab** [peter-gergely-horvath/windpapi4j#1]
Hi Peter,

thanks for the great DPAPI wrapper! I just wanted to let you know that I wrote a blog post about it: https://labs.consol.de/development/2017/03/27/protecting-passwords-in-java-properties-files.html

Fabian

**Comment by peter-gergely-horvath** [comment]
Hi Fabian,

It's great to hear it is useful for you. :) Thank you for the feedback and writing a great blog about the usage.

Cheers,
Peter
